apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default  # Specify the namespace here
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: rtx3osie/myapp:PLACEHOLDER  # Placeholder to be replaced by GitHub Actions
          ports:
            - containerPort: 3000
