apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: rtx3osie/myapp:${GITHUB_SHA}  # Replace with GitHub SHA dynamically in the pipeline
        ports:
        - containerPort: 3000  # Ensure this matches the targetPort in the Service
